### ISSUE TITLE
[Bug] Sometimes it will check type not variable name

### ISSUE THREAD

**Issue by JeffHsu79** [dougpuob/cpp-namelint#22]
![image](https://user-images.githubusercontent.com/54425769/63563887-4d592e80-c595-11e9-9952-263673f10fd4.png)
![image](https://user-images.githubusercontent.com/54425769/63563924-7679bf00-c595-11e9-8ac8-dd7a3ed68eb5.png)

**Comment by dougpuob** [comment]
This is because LLVM clang treats this Decl as an invalid decl, it may reference to unknown header files. 

I added a new option in config file, `BypassInvalidDecl`. I can be bypassed or indicated a include folder with -include command line option. This PR(https://github.com/dougpuob/cpp-namelint/pull/47) fixed the problem.
